export {
  CHANGE_RADIUS_COMMAND_TYPE,
  CHANGE_RADIUS_FAMILIES,
  CHANGE_RADIUS_LIMITS,
  CHANGE_RADIUS_SCHEMA_VERSION,
  MATERIALITIES,
  MATERIAL_TERM_KINDS,
  ChangeRadiusError,
} from "./types";

export type {
  AffectedRecord,
  AffectedChangeRecord,
  AffectedRecordBase,
  BeforeSourceVector,
  ArtifactAffectedRecord,
  ChangeRadiusErrorCode,
  ChangeRadiusFamily,
  ChangeRadiusMateriality,
  ChangeRadiusImpactAssertion,
  ChangeRadiusPolicy,
  ChangeRadiusPreflightResult,
  ChangeRadiusRecordReference,
  ChangeRadiusScope,
  ChangeRadiusSourceRecord,
  ChangeRadiusSourceVector,
  CommitmentAffectedRecord,
  ExactBeforeSourceVector,
  ImpactEdge,
  ImpactGraph,
  ImpactReason,
  JsonPrimitive,
  JsonValue,
  MaterialDurationTerm,
  MaterialRecordingTerm,
  MaterialRoleTerm,
  MaterialTermChange,
  MaterialTermComparison,
  MaterialTermKind,
  MaterialTermPolicy,
  MaterialTerms,
  MaterialTimeTerm,
  Materiality,
  OperatorReleaseAffectedRecord,
  PeopleAffectedRecord,
  ProposedChange,
  ProposedChangeEnvelope,
  ProposedChangeCommandEnvelope,
  ProposedImpactEdge,
  PublicReleaseAffectedRecord,
  ScheduleAffectedRecord,
  SourceVectorExpectation,
  UnknownAffectedRecord,
} from "./types";

export type { CanonicalValue } from "./canonical";

export {
  canonicalJson,
  cloneJsonValue,
  compareStableStrings,
  deepFreeze,
  fingerprint,
  isKnownFamily,
  outputFamily,
  recordKey,
  sameScope,
  scopeKey,
  sha256Hex,
  stableSort,
} from "./canonical";

export {
  canonicalMaterialTerms,
  compareMaterialTerms,
  compareTerms,
  isRoomOnlyVenueChange,
  materialTermComparator,
  materialityRank,
  maxMateriality,
} from "./material-terms";

export {
  calculateChangeRadius,
  analyzeChangeRadius,
  canonicalImpactGraphFingerprint,
  canonicalSourceVectorFingerprint,
  fingerprintImpactGraph,
  fingerprintSourceRecord,
  fingerprintSourceVector,
  preflight,
  preflightChangeRadius,
  preflightProposedChange,
  previewChangeRadius,
} from "./preflight";
