export const FORM_FIELD_TYPES = Object.freeze([
  "shortText",
  "longText",
  "richText",
  "singleChoice",
  "multipleChoice",
  "checkbox",
  "ranking",
  "matrix",
  "integer",
  "decimal",
  "date",
  "time",
  "dateTime",
  "email",
  "phone",
  "url",
  "address",
  "location",
  "fileUpload",
  "fileLink",
  "consent",
  "acknowledgement",
  "policyAcceptance",
  "personReference",
  "proposalOwnerReference",
  "coSpeakerReference",
  "section",
  "repeatableGroup",
  "calculated",
] as const);

export type FormFieldType = (typeof FORM_FIELD_TYPES)[number];
